version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

#job that spins up the creation of infrastructures with cloudformaation
jobs: 
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create cloudformation Stack
          command: |
            aws cloudformation deploy \
            --template-file server.yml \
            --parameter-overrides file://serverParams.json \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
            --region us-east-1
  
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["fb:dc:2d:cb:99:03:50:5d:34:1a:c6:ef:e9:60:22:59"]
      - run:
          name: Ansible Dependency Installation
          command: |
            apk add --update ansible
      - run:
          name: Configure Server
          command: |
            ansible-playbook -i inventory.txt main.yml
          expect:
            command: ansible-playbook -i inventory.txt main.yml
            responses:
              'FAre you sure you want to continue connecting (yes/no)?' : 'yes'


workflows:
  my_workflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure