version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

commands:
  # Rollback
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7}
jobs:

  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file server.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7} \
                --parameter-overrides file://serverParams.json \
                --region us-east-1
        - destroy_environment

  configure_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
                fingerprints: ["fb:dc:2d:cb:99:03:50:5d:34:1a:c6:ef:e9:60:22:59"] 
        - run:
            name: Install Ansible
            command: |
              # Install Ansible
              apk add --update ansible
        - run:
            name: Run Playbook and Configure server
            command: |
              # Your command  
              ansible-playbook -i inventory.txt main.yml  
  # Smoke Testing
  smoke_test:
      docker:
        - image: alpine:latest
      steps:
        - checkout
        - run:
            name: smoke test
            command: return 1                 
        - destroy_environment  
             
# Invoke jobs via workflows
workflows:
  my-workflow:
    jobs:
      - create_infrastructure
      #- configure_infrastructure
      - smoke_test:
            requires:
                - create_infrastructure