version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

#job that spins up the creation of infrastructures with cloudformation
jobs: 
  #Infrastructure Creation
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create cloudformation Stack
          command: |
            aws cloudformation deploy \
            --template-file server.yml \
            --parameter-overrides file://serverParams.json \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
            --region us-east-1
  
  #Configurations and Deployments
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["d1:af:f7:e9:98:b6:83:ba:4e:f6:06:b9:58:c8:e3:28:e8:77:99:2b"]
      - run:
          name: Ansible Dependency Installation
          command: |
            apk add --update ansible
      - run:
          name: Configure Server
          command: | 
            ansible-playbook -i inventory main.yml
          # expect:
          #   command: ansible-playbook -i inventory.txt main.yml
          #   responses:
          #     'Are you sure you want to continue connecting (yes/no)?' : 'yes'


workflows:
  my_workflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure